databases:
  - name: animate_db
    databaseName: animate_production
    user: animate
    plan: free

services:
  - type: web
    name: animate
    env: ruby
    plan: free
    runtime: ruby
    buildCommand: bundle install && RAILS_ENV=production bundle exec rails assets:precompile
    runtimeVersion: 3.3.0
    startCommand: bundle exec puma -t 5:5 -w 2 -p ${PORT:-3000} --preload -e ${RACK_ENV:-production}
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: animate_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: c314c778fafa4c656215794616f1868f
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: NODE_ENV
        value: production
